# Generated by Django 4.2.6 on 2023-10-18 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Date of create')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of update')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Категория груза',
                'verbose_name_plural': 'Категории грузов',
            },
        ),
        migrations.CreateModel(
            name='CargoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Date of create')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of update')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('code', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('type_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.cargocategoriesmodel')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
        migrations.CreateModel(
            name='PackingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Date of create')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of update')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('slug', models.SlugField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Упаковки',
            },
        ),
        migrations.CreateModel(
            name='StationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Date of create')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of update')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('slug', models.SlugField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
        migrations.CreateModel(
            name='WagonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Date of create')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of update')),
                ('type_wagon', models.CharField(max_length=256, unique=True)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Вагон',
                'verbose_name_plural': 'Вагоны',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Date of create')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of update')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dist', models.PositiveIntegerField(default=250)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('day', models.PositiveIntegerField(blank=True, null=True)),
                ('creat', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Создан'), (1, 'Оплачен'), (2, 'В пути'), (3, 'Доставлен')], default=0)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transportation.cargomodel')),
                ('first_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_from', to='transportation.stationmodel')),
                ('packing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transportation.packingmodel')),
                ('second_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_to', to='transportation.stationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wagon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transportation.wagonmodel')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
